
[functions.ping]
enabled = true
verify_jwt = true
import_map = "./functions/ping/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ping/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ping/*.html" ]

[functions.send-push-notifications]
enabled = true
verify_jwt = false
import_map = "./functions/send-push-notifications/deno.json"
entrypoint = "./functions/send-push-notifications/index.ts"
